name: Build iOS App
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Ruby (for CocoaPods)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
          cd ..
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Build iOS App
        run: |
          npx react-native run-ios --configuration Release --simulator="iPhone 15 Pro"
          
      - name: Archive iOS App
        run: |
          cd ios
          xcodebuild -workspace WinnipegCADMonitor.xcworkspace \
                     -scheme WinnipegCADMonitor \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath WinnipegCADMonitor.xcarchive \
                     archive
          cd ..
          
      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
                     -archivePath WinnipegCADMonitor.xcarchive \
                     -exportPath ./build \
                     -exportOptionsPlist ExportOptions.plist
          cd ..
          
      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/build/*.ipa
          retention-days: 30
          